language: node_js
# Make the filesystem case insensitive.... Because one of the lib we use is defective.... react-data-menu
os:
  - osx
node_js:
  - "4"
cache:
  directories:
    - node_modules
script:
    - npm run build-prod
notifications:
  email: false
#deploy:
#  provider: npm
#  skip_cleanup: true
#  email: jonathan.naim@gmail.com
#  api_key: $NPM_TOKEN
#  on:
#    tags: true
#    all_branches: true